### ISSUE TITLE
No max_execution_time timout

### ISSUE THREAD

**Issue by lordtatty** [jmunzer/bulk_tools#16]
It seems to be possible to set max_execution_time to be 0, and that will mean there will be no timeout for long running scripts.  

On a live web server this would be dangerous, but as this will be running on people's local machines it's just down to how long they want to keep their computer switched on. 

Background Reading:
https://stackoverflow.com/questions/7036767/how-can-i-get-infinite-maximum-execution-time-with-php
https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by jmunzer** [comment]
ah yeah.. we actually set this to zero as a test, to see whether it was effective, and never set it to something more thoughtful for other users.. 

600-1200s seems reasonable as a starting point. I'll have a read and review. Thanks for flagging this up Rich!

**Comment by jmunzer** [comment]
url tool set to 600.

**Comment by lordtatty** [comment]
Just to clarify I was actually suggesting setting it to ``0`` here as it's only running for users locally, so it can happily run for as long as needed.  

I'm not an expert on this parameter though, is there a reason we shouldn't do that?

**Comment by jmunzer** [comment]
Ah sorry, I read it that you were warning against doing so! I guess it's
better to guarantee an output after x minutes of running (and having to run
script multiple times) rather than a run potentially hanging for hours
before we know if there is an issue or not

Joe
