### ISSUE TITLE
Notice: Trying to get property 'link' of non-object in S:\xampp\htdocs\bulk_tools\url_complete\src\comp.php on line 190  

### ISSUE THREAD

**Issue by ichilvers** [jmunzer/bulk_tools#9]
https://github.com/jmunzer/bulk_tools/blob/6830a3bdea92ea65b6d45feea6d92b454d0fddb4/url_complete/src/comp.php#L190

Getting:
`Notice: Trying to get property 'link' of non-object in S:\xampp\htdocs\bulk_tools\url_complete\src\comp.php on line 190`  
when running items with "online_resource": null in the json data.

Not sure if there is/was an intention to use the link property of "online_resource", but $online_resource isn't used anywhere else in the script, so this line could possibly be removed or updated to ignore property of non-object notice.

It would help to clean up the output.

Thanks,
Ian

**Comment by jmunzer** [comment]
right you are! Great spot and thanks for the feedback. Lets strip it out. I basically built this url tool from the find and replace tool which is quite old code now. It seems a few lines are carried over into this tool and are just not needed at all!

Thanks :)

**Comment by timhodson** [comment]
have a look at the extra-guards branch

**Comment by ichilvers** [comment]
extra-guards branch is working well as far as I have been able to test
thanks Tim

**Comment by timhodson** [comment]
Great. We've actually incorporated those changes into the work that will become the revamped url updating tool.
This isn't live yet, but will be by Wednesday 22nd July :) .
